language: c
compiler:
  - gcc
matrix:
 include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7 gfortran-7

script: ./configure CC=gcc-7 FC=gfortran-7 && make && make test
